
export const FETCHING_CONTEST_REQUEST = "FETCHING_CONTEST_REQUEST";
export const FETCHING_CONTEST_SUCCESS = "FETCHING_CONTEST_SUCCESS";
export const FETCHING_CONTEST_FAILURE = "FETCHING_CONTEST_FAILURE";




